# This workflow will install Python dependencies, run the app, and ensure the server is running

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - uses: actions/checkout@v4

    # Step 2: Set up Python 3.10 environment
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # Step 3: Install dependencies via Makefile
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make install

    # Step 4: Run the application and allow the server time to start
    - name: Run the web application
      run: |
        make run &
        sleep 10  # Sleep to allow the server time to start

    # Step 5: Test whether the server is running on localhost:3000
    - name: Test server status
      run: |
        curl -I http://localhost:3000  # Check if the server responds
